### ISSUE TITLE
opentracing版本兼容性问题

### ISSUE THREAD

**Issue by hugoren** [songcser/sanic-ms#1]
opentracing==1.2.2 对python版本是>2.6 <3
sanic对python版本要求是3.5以上
请问你是如何解决这兼容性问题？
谢谢

**Comment by songcser** [comment]
不是opentracing对版本的要求，是opentracing依赖futures，最新的futrues对python版本需要<3，这个在最新的opentracing代码中将futures去掉了，现在可以先安装futrues以前的版本解决, 如'futures==3.1.1',

**Comment by hugoren** [comment]
good,  谢谢
