### ISSUE TITLE
utils.py里文件引用问题

### ISSUE THREAD

**Issue by hugoren** [songcser/sanic-ms#2]
1. 第108行引用了CustomException，这个CustomException是在exception里的类，  没有在utils引 用

2. 第82至 84行，引用的是同文件里的涵数id_to_hex，为何还要加上utils.id_to_hex(x)这样的引用方式

3.第139行的tags，不在涵数before_request里，也不在全局里定义，这应该是从from opentracing.ext import tags引用的，但 utils.py没有引用

谢谢

**Comment by hugoren** [comment]
我知道tags是从哪里来了
from opentracing.ext import tags， 但是utils.py里没有引用

**Comment by songcser** [comment]
谢谢你提的问题，是因为以前这些模块变量都是在server.py这个文件里的，最后才移到utils.py文件里的，后来就没有测试。
现在已经改过来了。

**Comment by hugoren** [comment]
good job
