### ISSUE TITLE
项目是如何启动的？

### ISSUE THREAD

**Issue by hugoren** [songcser/sanic-ms#4]
查看整个sanicms项目
    没发现app.run(***)
假如是用事件方式 执行 ，也没发现有这样
     loop = asyncio.get_event_loop()
    loop.run_until_complete(**))

请问是如何启动的？
谢谢

**Comment by songcser** [comment]
可以看一下这个例子：[example](https://github.com/songcser/sanic-ms/tree/master/examples)

**Comment by hugoren** [comment]
我已经加了，只是好奇在server没有app.run(**), 好奇是不是有什么更新奇的启动写法
