### ISSUE TITLE
有没有服务发现的解决方案啊?

### ISSUE THREAD

**Issue by huangxingx** [songcser/sanic-ms#7]

**Comment by songcser** [comment]
解决方案挺多的啊，主要是看哪个适合了。openresty和consul可以去做服务发现的，最好的是使用k8s.

**Comment by songcser** [comment]
解决方案挺多的，主要是看哪个适合了。openresty和consul可以去做服务发现的，最好的是使用k8s.

**Comment by huangxingx** [comment]
谢谢了， 以前不知道k8s还可以做服务发现， 受教了 ^_^
